const imgArray = [
   "./img/drinks/Apple cider vinegar 1.png",
   "./img/drinks/Apple cider vinegar black tea 1.png",
   "./img/drinks/Barley soy milk 1.png",
   "./img/drinks/Barley tea 1.png",
   "./img/drinks/Barley tea latte 1.png",
   "./img/drinks/Black tea 1.png",
   "./img/drinks/Black tea latte 1.png",
   "./img/drinks/Black tea latte with mashed sweet potato 1.png",
   "./img/drinks/Black tea latte with ruby chocolate 1.png",
   "./img/drinks/Black tea macchiato 1.png",
   "./img/drinks/Black tea soy milk 1.png",
   "./img/drinks/Blueberry vinegar 1.png",
   "./img/drinks/Blueberry vinegar black tea 1.png",
   "./img/drinks/Blueberry vinegar with aloe jelly 1.png",
   "./img/drinks/Blueberry vinegar yakult 1.png",
   "./img/drinks/Boba Black Tea 1.png",
   "./img/drinks/Boba black tea latte 1.png",
   "./img/drinks/Boba brown sugar milk 1.png",
   "./img/drinks/Boba coconut jelly oolong tea 1.png",
   "./img/drinks/Boba green milk tea 1.png",
   "./img/drinks/Boba green tea 1.png",
   "./img/drinks/Boba ice cream pudding black tea 1.png",
   "./img/drinks/Boba milk 1.png",
   "./img/drinks/Boba milk tea 1.png",
   "./img/drinks/Boba oolong milk tea 1.png",
   "./img/drinks/Boba oolong tea 1.png",
   "./img/drinks/Boba passion fruit green tea with coconut jelly 1.png",
   "./img/drinks/Boba sesame black tea latte 1.png",
   "./img/drinks/Brown sugar milk 1.png",
   "./img/drinks/Brown sugar milk with grass jelly 1.png",
   "./img/drinks/Cafe latte 1.png",
   "./img/drinks/Chocolate latte 1.png",
   "./img/drinks/Chocolate milk 1.png",
   "./img/drinks/Coconut jelly milk tea 1.png",
   "./img/drinks/Coffee black tea 1.png",
   "./img/drinks/Coffee jelly milk tea 1.png",
   "./img/drinks/Flowery black tea 1.png",
   "./img/drinks/Fresh yuzu juice 1.png",
   "./img/drinks/Fruity black tea 1.png",
   "./img/drinks/Ginger milk tea 1.png",
   "./img/drinks/Ginger tea 1.png",
   "./img/drinks/Grape juice with aloe vera jelly 1.png",
   "./img/drinks/Grapefruit green tea 1.png",
   "./img/drinks/Grapefruit juice 1.png",
   "./img/drinks/Grapefruit yakult 1.png",
   "./img/drinks/Grass jelly milk 1.png",
   "./img/drinks/Grass jelly milk tea 1.png",
   "./img/drinks/Green milk tea 1.png",
   "./img/drinks/Green milk tea with taro balls 1.png",
   "./img/drinks/Green tea latte 1.png",
   "./img/drinks/Green tea with pear juice and osmanthus agar pearl 1.png",
   "./img/drinks/Hojicha latte 1.png",
   "./img/drinks/Honey apple cider vinegar 1.png",
   "./img/drinks/Honey apple cider vinegar black tea 1.png",
   "./img/drinks/Honey blueberry vinegar 1.png",
   "./img/drinks/Honey boba puer tea latte 1.png",
   "./img/drinks/Honey green tea 1.png",
   "./img/drinks/Honey lemon juice 1.png",
   "./img/drinks/Honey lemon juice with aloe jelly 1.png",
   "./img/drinks/Honey milk tea 1.png",
   "./img/drinks/Honey oolong tea 1.png",
   "./img/drinks/Ice cream black tea 1.png",
   "./img/drinks/Ice cream matcha 1.png",
   "./img/drinks/Ice cream milk tea 1.png",
   "./img/drinks/Iced roselle plum juice 1.png",
   "./img/drinks/Iced roselle with green tea smoothie 1.png",
   "./img/drinks/Jasmine green tea 1.png",
   "./img/drinks/Kumquat green tea 1.png",
   "./img/drinks/Kumquat juice 1.png",
   "./img/drinks/Kumquat lemonade 1.png",
   "./img/drinks/Kumquat plum green tea 1.png",
   "./img/drinks/Kumquat plum juice 1.png",
   "./img/drinks/Lemon black tea 1.png",
   "./img/drinks/Lemon green tea 1.png",
   "./img/drinks/Lemon ice shavings black tea 1.png",
   "./img/drinks/Lemon ice shavings green tea 1.png",
   "./img/drinks/Lemon ice shavings oolong tea 1.png",
   "./img/drinks/Lemon juice 1.png",
   "./img/drinks/Lemon plum green tea 1.png",
   "./img/drinks/Lemon plum juice 1.png",
   "./img/drinks/Lemon winter melon tea 1.png",
   "./img/drinks/Lemon yakult 1.png",
   "./img/drinks/Longan ginger tea 1.png",
   "./img/drinks/Longan latte 1.png",
   "./img/drinks/Longan milk tea 1.png",
   "./img/drinks/Longan red dates tea 1.png",
   "./img/drinks/Mashed sweet potato milk tea 1.png",
   "./img/drinks/Matcha latte 1.png",
   "./img/drinks/Matcha latte with ruby chocolate 1.png",
   "./img/drinks/Matcha with passion fruit konjac jelly 1.png",
   "./img/drinks/Milk coffee 1.png",
   "./img/drinks/Milk tea 1.png",
   "./img/drinks/Millet mush milk tea 1.png",
   "./img/drinks/Mung bean smoothie with thick milk 1.png",
   "./img/drinks/Oolong green tea 1.png",
   "./img/drinks/Oolong macchiato 1.png",
   "./img/drinks/Oolong milk tea 1.png",
   "./img/drinks/Oolong soy milk 1.png",
   "./img/drinks/Oolong tea 1.png",
   "./img/drinks/Oolong tea latte 1.png",
   "./img/drinks/Oolong tea with mashed sweet potato 1.png",
   "./img/drinks/Orange green tea 1.png",
   "./img/drinks/Orange ice shavings green tea 1.png",
   "./img/drinks/Orange oolong tea 1.png",
   "./img/drinks/OREO cocoa smoothie 1.png",
   "./img/drinks/Ovaltine 1.png",
   "./img/drinks/Ovaltine latte 1.png",
   "./img/drinks/Peach black tea 1.png",
   "./img/drinks/Peach black tea with yakult 1.png",
   "./img/drinks/Pearl black tea 1.png",
   "./img/drinks/Pearl black tea latte 1.png",
   "./img/drinks/Pearl green milk tea 1.png",
   "./img/drinks/Pearl green tea 1.png",
   "./img/drinks/Pearl milk tea 1.png",
   "./img/drinks/Pearl oolong milk tea 1.png",
   "./img/drinks/Pearl oolong tea 1.png",
   "./img/drinks/Pineapple black tea 1.png",
   "./img/drinks/Plum green tea 1.png",
   "./img/drinks/Plum winter melon tea 1.png",
   "./img/drinks/Pudding black tea 1.png",
   "./img/drinks/Pudding green milk tea 1.png",
   "./img/drinks/Pudding green tea 1.png",
   "./img/drinks/Pudding milk tea 1.png",
   "./img/drinks/Pudding oolong tea 1.png",
   "./img/drinks/Puer tea 1.png",
   "./img/drinks/Rice grain oolong milk tea 1.png",
   "./img/drinks/Sesame milk tea 1.png",
   "./img/drinks/Sugarcane oolong tea 1.png",
   "./img/drinks/Taro ball green tea latte 1.png",
   "./img/drinks/Taro ball milk tea 1.png",
   "./img/drinks/Taro green tea latte 1.png",
   "./img/drinks/Taro milk 1.png",
   "./img/drinks/Taro milk tea 1.png",
   "./img/drinks/Taro milk with boba coconut jelly small taro balls 1.png",
   "./img/drinks/Taro milk with boba coconut jelly taro balls 1.png",
   "./img/drinks/Taro milk with boba red beans taro balls and sago 1.png",
   "./img/drinks/Taro milk with sago 1.png",
   "./img/drinks/Taro milk with taro balls 1.png",
   "./img/drinks/Taro milkshake 1.png",
   "./img/drinks/Taro milkshake with purple sweet potato boba 1.png",
   "./img/drinks/Taro milkshake with red beans 1.png",
   "./img/drinks/Taro smoothie with mango and sago 1.png",
   "./img/drinks/Tropical fruit tea 1.png",
   "./img/drinks/Winter melon barley tea 1.png",
   "./img/drinks/Winter melon black tea 1.png",
   "./img/drinks/Winter melon green tea 1.png",
   "./img/drinks/Winter melon oolong tea 1.png",
   "./img/drinks/Winter melon tea 1.png",
   "./img/drinks/Winter melon tea latte 1.png",
   "./img/drinks/Winter melon tea with agar pearl and boba and wood ear 1.png",
   "./img/drinks/Winter melon tea with agar pearl and sago and wood ear 1.png",
   "./img/drinks/Winter melon tea with grass jelly 1.png",
   "./img/drinks/Winter melon tea with taro balls 1.png",
   "./img/drinks/Winter melon tea with wood ear 1.png",
   "./img/drinks/Yakult green tea 1.png",
   "./img/drinks/Yakult green tea with aloe jelly 1.png",
   "./img/drinks/Yuzu green tea 1.png",
   "img/categories/Agar pearl t.png",
"img/categories/Aloe jelly t.png",
"img/categories/Apple cider vinegar b1.png",
"img/categories/Barley tea b1.png",
"img/categories/Black tea b1.png",
"img/categories/Black tea b2.png",
"img/categories/Blueberry cider vinegar b1.png",
"img/categories/Blueberry cider vinegar.png",
"img/categories/Boba coconut jelly t.png",
"img/categories/Boba coconut jelly taro balls t.png",
"img/categories/Boba ice cream pudding t.png",
"img/categories/Boba purple sweet potatoes t.png",
"img/categories/Boba t.png",
"img/categories/Boba taro balls sago red beans t.png",
"img/categories/Boba wood ear agar pearl t.png",
"img/categories/Brown sugar f.png",
"img/categories/Cocoa f.png",
"img/categories/Coconut jelly t.png",
"img/categories/Coffee b1.png",
"img/categories/Coffee b2.png",
"img/categories/Coffee jelly t.png",
"img/categories/Dried longan t.png",
"img/categories/Faucet.png",
"img/categories/Flower tea b2.png",
"img/categories/Fresh cream m.png",
"img/categories/Fresh milk m.png",
"img/categories/Fruit tea b2.png",
"img/categories/Ginger tea b1.png",
"img/categories/Ginger tea b2.png",
"img/categories/Grape juice b1.png",
"img/categories/Grapefruit juice b1.png",
"img/categories/Grapefruit juice b2.png",
"img/categories/Grass jelly t.png",
"img/categories/Green tea b1.png",
"img/categories/Green tea b2.png",
"img/categories/Hojicha b1.png",
"img/categories/Honey f.png",
"img/categories/Ice b1.png",
"img/categories/Ice b2.png",
"img/categories/Ice cream t.png",
"img/categories/Ice shavings t.png",
"img/categories/Konjac jelly t.png",
"img/categories/Kumquat juice b1.png",
"img/categories/Kumquat juice b2.png",
"img/categories/Kumquat plum juice b2.png",
"img/categories/Lemon juice b1.png",
"img/categories/Lemon juice b2.png",
"img/categories/Lemon plum juice b2.png",
"img/categories/Mango juice b1.png",
"img/categories/Mashed sweet potato t.png",
"img/categories/Matcha tea b1.png",
"img/categories/Milk powder m.png",
"img/categories/Millet mush t.png",
"img/categories/Mixed fruit juice b2.png",
"img/categories/Mung bean puree f.png",
"img/categories/Oolong tea b1.png",
"img/categories/Oolong tea b2.png",
"img/categories/Orange juice b1.png",
"img/categories/Orange juice b2.png",
"img/categories/OREO t.png",
"img/categories/Osmanthus agar pearl t.png",
"img/categories/Ovaltine b1.png",
"img/categories/Passion fruit juice b2.png",
"img/categories/Passionfruit puree f.png",
"img/categories/Peach f.png",
"img/categories/Peach tea b2.png",
"img/categories/Pear juice b2.png",
"img/categories/Pearl t.png",
"img/categories/Pineapple chunk t.png",
"img/categories/Pineapple juice b2.png",
"img/categories/Plum juice b2.png",
"img/categories/Plum tea b2.png",
"img/categories/Pudding t.png",
"img/categories/Puer tea b1.png",
"img/categories/Purple sweet potato boba t.png",
"img/categories/Purple sweet potatoes t.png",
"img/categories/Red beans t.png",
"img/categories/Red dates tea b1.png",
"img/categories/Rice grain t.png",
"img/categories/Roselle juice b2.png",
"img/categories/Roselle plum juice b1.png",
"img/categories/Sago t.png",
"img/categories/Sago wood ear agar pearl t.png",
"img/categories/Sesame f.png",
"img/categories/Soy milk m.png",
"img/categories/Sugarcane juice b2.png",
"img/categories/Taro balls t.png",
"img/categories/Taro puree f.png",
"img/categories/Winter melon tea b1.png",
"img/categories/Winter melon tea b2.png",
"img/categories/Wood ear t.png",
"img/categories/Yakult b1.png",
"img/categories/Yakult b2.png",
"img/categories/Yuzu juice b1.png",
"img/categories/Yuzu juice b2.png"
];
